# Basic Information 
title: Felix Jäger
position: Ph.D. Student
affiliation: Department of Eco-evolutionary modelling, University of Hohenheim, Stuttgart
affiliation_link: https://eco-evolutionary-modelling.uni-hohenheim.de/en/english
email: felix.jaeger (at) uni-hohenheim.de

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: felix jaeger, felix jäger
description: Academic personal homepage of Felix Jäger
canonical: https://minimal-light-theme.yliu.me/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?hl=de&user=u397Pj8AAAAJ&view_op=list_works

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Sans Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
